version: "3.8"
services:
  vprodb:
    build: 
      context: ./Docker-files/db/
    image: harshad75/vprofiledb
    container_name: vprodb
    environment: 
      - MYSQL_ROOT_PASSWORD=vprodbpass
    ports:
      - "3306:3306"
    volumes: 
      - vprodbdata:/var/lib/mysql

  vprocache01:
    image: memcached
    ports: 
      - "11211:11211"

  vprormq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: 
      context: ./Docker-files/app/
    image: harshad75/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
      context: ./Docker-files/web/
    ports:
      - "80:80"
    image: harshad75/vprofileweb
    container_name: vproweb

volumes: 
  vprodbdata: {}
  vproappdata: {}